### PR TITLE
update: improve logging, debug and devtools

### PR DESCRIPTION
**Pull request by knokbak**

### CODE REVIEW

**Comment by PalmDevs** [comment]
Do I really have to do `git pull` again?
God damn it.

**Comment by axisiscool** [comment]
@knokbak stop requesting my review if you're just going to merge it

**Comment by knokbak** [comment]
> @knokbak stop requesting my review if you're just going to merge it

it's github automatically adding you 😂
i'll see what i can change

**Comment by axisiscool** [comment]
> > @knokbak stop requesting my review if you're just going to merge it
> 
> 
> 
> it's github automatically adding you 😂
> 
> i'll see what i can change

Thanks! I don't mind usually but I go to review and u merge haha

**Comment by knokbak** [comment]
> > > @knokbak stop requesting my review if you're just going to merge it
> > 
> > 
> > it's github automatically adding you 😂
> > i'll see what i can change
> 
> Thanks! I don't mind usually but I go to review and u merge haha

it *shouldn't* automatically request your review now. the real question is whether or not it *will*

**Pull request merged**
